### ISSUE TITLE
MYSQL Save

### ISSUE THREAD

**Issue by GravityScriptsV2** [uniqscripts/uniq-playtime#1]
[      script:oxmysql] SCRIPT ERROR in promise (unhandled rejection): Error: uniq-playtime was unable to execute a query!
[      script:oxmysql] Truncated incorrect DECIMAL value: 'BQG80800'
[      script:oxmysql] UPDATE `players` SET playTime = playTime + ? WHERE citizenid = ? ["GQU08159",22]

**Comment by katotekii** [comment]
Hi, show me your `players` column in sql

**Comment by GravityScriptsV2** [comment]
<table caption="players (8 rows)">
      <thead>
        <tr>
          <th class="col0">id</th>
          <th class="col1">citizenid</th>
          <th class="col2">cid</th>
          <th class="col3">license</th>
          <th class="col4">name</th>
          <th class="col5">money</th>
          <th class="col6">charinfo</th>
          <th class="col7">job</th>
          <th class="col8">gang</th>
          <th class="col9">position</th>
          <th class="col10">metadata</th>
          <th class="col11">inventory</th>
          <th class="col12">last_updated</th>
          <th class="col13">mugshot</th>
          <th class="col14">apps</th>
          <th class="col15">widget</th>
          <th class="col16">bt</th>
          <th class="col17">cryptocurrency</th>
          <th class="col18">cryptocurrencytransfers</th>
          <th class="col19">phonePos</th>
          <th class="col20">spotify</th>
          <th class="col21">ringtone</th>
          <th class="col22">first_screen_showed</th>
          <th class="col23">phone</th>
          <th class="col24">iban</th>
          <th class="col25">twitteraccount</th>
          <th class="col26">settings</th>
          <th class="col27">calls</th>
          <th class="col28">notes</th>
          <th class="col29">photos</th>
          <th class="col30">darkchatuser</th>
          <th class="col31">mailaccount</th>
          <th class="col32">playTime</th>
        </tr>
      </thead>

**Comment by GravityScriptsV2** [comment]
is this what you wanted?

**Comment by GravityScriptsV2** [comment]
https://cdn.discordapp.com/attachments/715268958076534805/1108518371953213482/image.png
https://cdn.discordapp.com/attachments/715268958076534805/1108518418405130240/image.png 
or this?

**Comment by katotekii** [comment]
![image](https://github.com/uniqscripts/uniq-playtime/assets/58405477/c85598d2-82a9-47f9-8e68-f76f4ec80a15)
this one

**Comment by GravityScriptsV2** [comment]
[](https://cdn.discordapp.com/attachments/715268958076534805/1108898537250496523/image.pngl)

**Comment by GravityScriptsV2** [comment]
![image](https://github.com/uniqscripts/uniq-playtime/assets/95504918/d47308d6-0272-4e54-85c0-af4b99444136)

**Comment by GravityScriptsV2** [comment]
![image](https://github.com/uniqscripts/uniq-playtime/assets/95504918/48cfb200-05cc-48d3-a8c9-a1b6ee3376a5)

**Comment by katotekii** [comment]
where did you got that qb core, why you have `armscii8_bin`, it should be `utf8mb4_general_ci`

**Comment by katotekii** [comment]
download latest release, you should be good now

**Comment by GravityScriptsV2** [comment]
when I change armscii8_bin to utf8mb4_general_ci it gives me a error and i got it from the qb-core framework github and I have tried the latest release and still getting same issue 
![image_2023-05-19_193957063](https://github.com/uniqscripts/uniq-playtime/assets/95504918/c3d92914-8625-4192-9e87-918f0bc8eba2)

**Comment by GravityScriptsV2** [comment]
this issue is still on going after latest release of uniq playtime

**Comment by katotekii** [comment]
you still get `UPDATE players SET playTime = playTime + ? WHERE citizenid = ? ["GQU08159",22]` ??

**Comment by GravityScriptsV2** [comment]
yea and I am on the latest

**Comment by GravityScriptsV2** [comment]
it say  
[      script:oxmysql] SCRIPT ERROR in promise (unhandled rejection): Error: uniq-playtime was unable to execute a query!
[      script:oxmysql] Truncated incorrect DECIMAL value: 'BQG80800'
[      script:oxmysql] UPDATE `players` SET playTime = playTime + ? WHERE citizenid = ? ["GQU08159",17]
[      script:oxmysql] > <unknown> (@oxmysql/dist/build.js:21833)
[      script:oxmysql] > processTicksAndRejections (node:internal/process/task_queues:96)
[      script:oxmysql]

**Comment by katotekii** [comment]
that is code from old release, get latest

**Comment by GravityScriptsV2** [comment]
I did get the latest release, I literally remember downloading the repo again and replacing it

**Comment by GravityScriptsV2** [comment]
but I try again

**Comment by GravityScriptsV2** [comment]
ok now it working thanks
