### ISSUE TITLE
Enchantment | More ways to show time

### ISSUE THREAD

**Issue by GravityScriptsV2** [uniqscripts/uniq-playtime#2]
Ok so basically, say you wanna have the time display on another resource like for example loading screen, make it so you can have a export to where you can use it in another resource. that will show the playtime for each character you have aka license or whatever and then it will gather up all the seconds and make it like days, etc.

**Comment by katotekii** [comment]
`fetchTime` export was added, down there is example of usage
```lua
local xPlayer = ESX.GetPlayerFromId(source)

if xPlayer then
    local identifier = xPlayer.identifier

    local playerTime = exports['uniq-playtime']:fetchTime(identifier)

    if playerTime then
        print(playerTime)
    end
end
```
